### ISSUE TITLE
Genom tf-idf identifiera de mest signifikanta orden i SOU-materialet/år

### ISSUE THREAD

**Issue by fredrik1984** [humlab/welfare_state_analytics#25]
En viktiga fråga för Westac är: går det att identifiera ord/begrepp som är signifikanta för efterkrigsperioden, och vilka var isf dessa ord/begrepp?

Med SOU-materialet som ett test-case skulle en metod för att utforska frågan vara att implementera tf-idf. Dvs göra det möjligt att identifiera topp signifikanta ord per år givet tf-idf-metriken.

En utmaning är här SOU-materialets karaktär. Varje utredning handlar om en specifik sak, vilket såklart kan påverka tf-idf-resultatet. Här behövs de laboreras med olika sätt att "tona ner" det signifikanta. Till exempel utreddes hästavel 1982. Men det vore ju korrekt att ordet "hästavel" är signifikant för just det året. Det vi vill få fram är snarare signifikanta ord som är något mer generella, som "information", "planera" eller "bidrag".

Ett alternativ är kanske att fokusera på längre tidsperioder, kanske perioder om fem år, och identifiera topp signifikanta ord för dessa tidsintervall.

**Comment by roger-mahler** [comment]
Resolved by https://github.com/humlab/welfare_state_analytics/commit/d5556a8fd39ea73e85526231a0ce01739b590a82.
