### ISSUE TITLE
ny modell med 190 eller 210 topics

### ISSUE THREAD

**Issue by Stubbendorff** [humlab/welfare_state_analytics#56]
Måns tyckte att vi skulle ta fram en annan men snarlik modell att ha som kontrolldata för att säkerställa att de mönster vi ser i 200-modellen inte är resultatet av tillfällig- eller tokigheter. Han föreslog att vi kollade på något näraliggande, exempelvis 190 eller 210 topics.

**Comment by roger-mahler** [comment]
Uploaded to Drive.
