### ISSUE TITLE
Implementera most discriminating terms-metoden på de politiska textblocken 

### ISSUE THREAD

**Issue by fredrik1984** [humlab/welfare_state_analytics#57]
Vi vill kunna jämföra hur olika tidsperioders vokabulär skiljer sig åt  i tidningsdatat med textblocken som innehåller det politiska. Textblocken är redan rensade på stoppord och ord som bara förekommer fem gånger eller mindre. Men rensa även bort ord som finns bifogat i den kompletterande stoppordslistan här.

>Implementera most discriminating terms-metoden. 
>Det ska vara möjlighet att välja vilken tidsperiod vi vill jämföra (t ex 1950-talet mot 1970-talet) samt tidning (ab, dn eller båda)

[Uppdaterad stoppordslista.xlsx](https://github.com/humlab/welfare_state_analytics/files/4375675/Uppdaterad.stoppordslista.xlsx)

**Comment by roger-mahler** [comment]
## Most Discriminating Terms

New notebook named `4_mdw.ipynb` added in the `political_in_newspapers` folder.

Note! The computation can take **a very long time** depending on corpus size and arguments. It might be preferable to use the CLI version named `mdw_runner.py` instead.

### Example CLI call
Compare AB 1949-1949 to DN 1989-1989. Only the 200 top words are included in the computation, and at most 100 words are returned per group. Words that occur in few documents ( less than 3%), and many documents (more than 95%) are filtered out.

```
python mdw_runner.py --group AB 1945 1949 --group DN 1985 1989 --top-n-terms 200 --max-n-terms 100 --min-df 3.0 --max-df 95.0 

```
The result is stored in an excel file which is named based on the execution parameters.

**Comment by roger-mahler** [comment]
I suggest you try it out with shorter periods and a limited number of `--top-n-terms` terms.

**Comment by roger-mahler** [comment]
The stop word list is not used in this  since removal of words don't affect the computation.
