### ISSUE TITLE
Skapa ytterligare en 200-topicmodell för att kvalitetssäkra resultat

### ISSUE THREAD

**Issue by fredrik1984** [humlab/welfare_state_analytics#61]
För att öka robustheten i våra resonemang i papret om det politiska i tidningsdatat behöver vi skapa ytterligare en 200-topicmodell (på ab + dn, 1945–1989) för att undersöka om vi får liknande resultat.

Lägg upp färdig modell i Drive.

Tack!

**Comment by roger-mahler** [comment]
Data is now available on Google Drive.
