### ISSUE TITLE
Köra NER på de politiska textblocken

### ISSUE THREAD

**Issue by Gunnarnordahl** [humlab/welfare_state_analytics#69]
Kan vi köra ner på de politiska textblocken vi fått från KB? Hur är det, visst har vi både ett filtrerat dataset (där det är en svans borttagen) och hela kalaset? Vilka var nu igen kriterierna för det filtrerade datasetet?

**Comment by fredrik1984** [comment]
Från det arbetet som vi utförde i höstas inför Göteborgskonferensen så har vi alla ordfönster (8 + 1 + 8) för det politiska i intakt ordning. Jag tror det finns en sådan fil på Drive, jag har iaf en fil på min dator.

När det gäller textblocken (i olika storlekar), som vi körde topic modeling på, så har vi dessa också – men i omkastad ordning.

Det går såldes att köra NER på ordfönstren, men eftersom det bara är mindre fönster så är jag inte så säker på att det blir något bra resultat. Att köra NER på textblocken blir garanterat ännu mer knas eftersom där är alla ord omkastade. 

Ett annat alternativ är ju att köra NER på materialet från KBLab och sedan hämta hem resultatet i någon liknande matris som vi körde topic modeling på. Alltså en matris som anger vilka entities som är kopplade till textblocken. Möjligen kan man även få ut samförekomstlistor med vilka ord som ligger närmast en viss plats-entitet t ex. Men det kräver förmodligen en del förarbete och man tänker igenom vad det är man vill göra med resultatet.

**Comment by roger-mahler** [comment]
Data är problematiskt med avhuggna meningar och allt i lowercase. Upper-case är rätt så signifikat för att identifiera personnamn och platser. Kört på det material som Fredrik föreslog dvs. med `politiska` +/- 8 ord i rätt ordning.
