### ISSUE TITLE
Hämta riksdagsdebatter 1945–1989 via KBLabs API

### ISSUE THREAD

**Issue by fredrik1984** [humlab/welfare_state_analytics#70]
Kan vi hämta hem riksdagsdebatterna (alltså kammarens protokoll) från KBLabs API?

Tanken är att vi ska börja använda det materialet till de två fallstudier som Johan och jag (Fredrik) ska börja arbeta med tillsammans med Måns. Om materialet finns tillgängligt via deras API kan vi tanka hem det för 1945–1989. Då kan Måns använda det när han nu ska börja utveckla modeller för att studera begrepps förändring över tid.

Jag har såklart redan bett KBLab att få ut detta material men det går trögt, bland annat på grund av corona. Om det finns ett snabbare sätt att komma igång så tänker jag att vi kan börja med det.

**Comment by roger-mahler** [comment]
Jag kan inte se att det finns tillgängligt via KB-LABs API. Ifall du surfar in på [https://betalab.kb.se](https://betalab.kb.se) med demo-användaren så är endast SOU och AB tillgängliga. Har du indikation på annat, eller tillgång till icke-demo användare?

**Comment by roger-mahler** [comment]
Closing in favor of #72.
