### ISSUE TITLE
Skapa Jupyter-sida för att mäta ords frekvenser över tid i Riksdagsprotokollen

### ISSUE THREAD

**Issue by fredrik1984** [humlab/welfare_state_analytics#71]
Skapa en Jupyter-sida som gör det möjligt att mäta ords frekvenser över tid, baserat på de Riksdagsprotokoll som ligger uppe i KBLabs API. Vi börjar med den råa datan (senare kan det bli aktuellt att PoS-tagga materialet).

Det ska vara möjligt att välja ett eller flera ord som man vill följa frekvensen för över tid (år). 

Der ska gå att välja att följa frekvensen som trend-graf, stapeldiagram eller en data-tabell (som man kan ladda ner som cvs-fil för vidare analys).

Det vore också bra om det finns en funktion för se vilka protokoll som innehåller det eller de aktuella orden för ett visst år.

**Comment by fredrik1984** [comment]
...gällande frekvens över tid vore det såklart bra om man både kan se den relativa och den absoluta frekvensen

**Comment by roger-mahler** [comment]
Closing in favor of #78.
