### ISSUE TITLE
Skapa en korpus med Riksdagsprotokollen som txt

### ISSUE THREAD

**Issue by fredrik1984** [humlab/welfare_state_analytics#72]
Skapa en korpus där alla Riksdagsprotokoll samlas som txt-dokument

De enskilda dokumenten (protokollen) ska vara döpta efter år och id-nummer, som t ex här:
https://weburn.kb.se/riks/metadata/83/19569883.html

Notera att fram till 1970 fanns det två olika Riksdagskammare och därmed två olika typer av protokoll: första och andra kammarens protokoll. Detta bör också indikeras i titeln på dokumenten.

Denna korpus kan t ex förvaras på Github

**Comment by roger-mahler** [comment]
Corpus `HUMLAB/riksdagens_protokoll_content_corpus.zip` containing all available protocols between 1971 and 1989 has been uploaded to Google Drive project folder .

**Comment by roger-mahler** [comment]
Corpus `HUMLAB/riksdagens_protokoll_content_corpus_1945-1989.zip` added to Google Drive project folder.

Upper house  ("Första kammaren") protocols prior to 1970 have letters `_fk_` in the filename, and lower house protocols have `_fk_`.
